/*
 * This file is generated by jOOQ.
 */
package com.example.managestudentjooq.model.tables.records;


import com.example.managestudentjooq.model.tables.Subjects;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectsRecord extends UpdatableRecordImpl<SubjectsRecord> implements Record6<Integer, String, String, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>manage_students.subjects.id</code>.
     */
    public SubjectsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>manage_students.subjects.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>manage_students.subjects.name</code>.
     */
    public SubjectsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>manage_students.subjects.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>manage_students.subjects.description</code>.
     */
    public SubjectsRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>manage_students.subjects.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>manage_students.subjects.create_at</code>.
     */
    public SubjectsRecord setCreateAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>manage_students.subjects.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>manage_students.subjects.updated_at</code>.
     */
    public SubjectsRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>manage_students.subjects.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>manage_students.subjects.status</code>.
     */
    public SubjectsRecord setStatus(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>manage_students.subjects.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Subjects.SUBJECTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Subjects.SUBJECTS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Subjects.SUBJECTS.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Subjects.SUBJECTS.CREATE_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Subjects.SUBJECTS.UPDATED_AT;
    }

    @Override
    public Field<Integer> field6() {
        return Subjects.SUBJECTS.STATUS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public Integer component6() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public Integer value6() {
        return getStatus();
    }

    @Override
    public SubjectsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SubjectsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SubjectsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SubjectsRecord value4(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public SubjectsRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SubjectsRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public SubjectsRecord values(Integer value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectsRecord
     */
    public SubjectsRecord() {
        super(Subjects.SUBJECTS);
    }

    /**
     * Create a detached, initialised SubjectsRecord
     */
    public SubjectsRecord(Integer id, String name, String description, LocalDateTime createAt, LocalDateTime updatedAt, Integer status) {
        super(Subjects.SUBJECTS);

        setId(id);
        setName(name);
        setDescription(description);
        setCreateAt(createAt);
        setUpdatedAt(updatedAt);
        setStatus(status);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SubjectsRecord
     */
    public SubjectsRecord(com.example.managestudentjooq.model.tables.pojos.Subjects value) {
        super(Subjects.SUBJECTS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setCreateAt(value.getCreateAt());
            setUpdatedAt(value.getUpdatedAt());
            setStatus(value.getStatus());
            resetChangedOnNotNull();
        }
    }
}
