/*
 * This file is generated by jOOQ.
 */
package com.example.managestudentjooq.model;


import com.example.managestudentjooq.model.tables.Account;
import com.example.managestudentjooq.model.tables.Role;
import com.example.managestudentjooq.model.tables.StudentSubject;
import com.example.managestudentjooq.model.tables.Students;
import com.example.managestudentjooq.model.tables.Subjects;


/**
 * Convenience access to all tables in manage_students.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>manage_students.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>manage_students.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>manage_students.student_subject</code>.
     */
    public static final StudentSubject STUDENT_SUBJECT = StudentSubject.STUDENT_SUBJECT;

    /**
     * The table <code>manage_students.students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>manage_students.subjects</code>.
     */
    public static final Subjects SUBJECTS = Subjects.SUBJECTS;
}
