/*
 * This file is generated by jOOQ.
 */
package com.example.managestudentjooq.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String username;
    private String password;
    private LocalDateTime createAt;
    private LocalDateTime updatedAt;
    private Integer status;
    private Integer roleId;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.createAt = value.createAt;
        this.updatedAt = value.updatedAt;
        this.status = value.status;
        this.roleId = value.roleId;
    }

    public Account(
        Integer id,
        String username,
        String password,
        LocalDateTime createAt,
        LocalDateTime updatedAt,
        Integer status,
        Integer roleId
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.createAt = createAt;
        this.updatedAt = updatedAt;
        this.status = status;
        this.roleId = roleId;
    }

    /**
     * Getter for <code>manage_students.account.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>manage_students.account.id</code>.
     */
    public Account setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>manage_students.account.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>manage_students.account.username</code>.
     */
    public Account setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>manage_students.account.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>manage_students.account.password</code>.
     */
    public Account setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>manage_students.account.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>manage_students.account.create_at</code>.
     */
    public Account setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
        return this;
    }

    /**
     * Getter for <code>manage_students.account.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>manage_students.account.updated_at</code>.
     */
    public Account setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>manage_students.account.status</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>manage_students.account.status</code>.
     */
    public Account setStatus(Integer status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>manage_students.account.role_id</code>.
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>manage_students.account.role_id</code>.
     */
    public Account setRoleId(Integer roleId) {
        this.roleId = roleId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Account other = (Account) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.createAt == null) {
            if (other.createAt != null)
                return false;
        }
        else if (!this.createAt.equals(other.createAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!this.roleId.equals(other.roleId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.createAt == null) ? 0 : this.createAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(status);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
