/*
 * This file is generated by jOOQ.
 */
package com.example.managestudentjooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private Integer status;

    public Role() {}

    public Role(Role value) {
        this.id = value.id;
        this.name = value.name;
        this.status = value.status;
    }

    public Role(
        Integer id,
        String name,
        Integer status
    ) {
        this.id = id;
        this.name = name;
        this.status = status;
    }

    /**
     * Getter for <code>manage_students.role.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>manage_students.role.id</code>.
     */
    public Role setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>manage_students.role.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>manage_students.role.name</code>.
     */
    public Role setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>manage_students.role.status</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>manage_students.role.status</code>.
     */
    public Role setStatus(Integer status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Role other = (Role) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
