/*
 * This file is generated by jOOQ.
 */
package com.example.managestudentjooq.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Students implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String fullName;
    private Integer age;
    private Integer gender;
    private LocalDateTime createAt;
    private LocalDateTime updatedAt;
    private Integer status;

    public Students() {}

    public Students(Students value) {
        this.id = value.id;
        this.fullName = value.fullName;
        this.age = value.age;
        this.gender = value.gender;
        this.createAt = value.createAt;
        this.updatedAt = value.updatedAt;
        this.status = value.status;
    }

    public Students(
        Integer id,
        String fullName,
        Integer age,
        Integer gender,
        LocalDateTime createAt,
        LocalDateTime updatedAt,
        Integer status
    ) {
        this.id = id;
        this.fullName = fullName;
        this.age = age;
        this.gender = gender;
        this.createAt = createAt;
        this.updatedAt = updatedAt;
        this.status = status;
    }

    /**
     * Getter for <code>manage_students.students.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>manage_students.students.id</code>.
     */
    public Students setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>manage_students.students.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>manage_students.students.full_name</code>.
     */
    public Students setFullName(String fullName) {
        this.fullName = fullName;
        return this;
    }

    /**
     * Getter for <code>manage_students.students.age</code>.
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>manage_students.students.age</code>.
     */
    public Students setAge(Integer age) {
        this.age = age;
        return this;
    }

    /**
     * Getter for <code>manage_students.students.gender</code>.
     */
    public Integer getGender() {
        return this.gender;
    }

    /**
     * Setter for <code>manage_students.students.gender</code>.
     */
    public Students setGender(Integer gender) {
        this.gender = gender;
        return this;
    }

    /**
     * Getter for <code>manage_students.students.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>manage_students.students.create_at</code>.
     */
    public Students setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
        return this;
    }

    /**
     * Getter for <code>manage_students.students.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>manage_students.students.updated_at</code>.
     */
    public Students setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>manage_students.students.status</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>manage_students.students.status</code>.
     */
    public Students setStatus(Integer status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Students other = (Students) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.age == null) {
            if (other.age != null)
                return false;
        }
        else if (!this.age.equals(other.age))
            return false;
        if (this.gender == null) {
            if (other.gender != null)
                return false;
        }
        else if (!this.gender.equals(other.gender))
            return false;
        if (this.createAt == null) {
            if (other.createAt != null)
                return false;
        }
        else if (!this.createAt.equals(other.createAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.age == null) ? 0 : this.age.hashCode());
        result = prime * result + ((this.gender == null) ? 0 : this.gender.hashCode());
        result = prime * result + ((this.createAt == null) ? 0 : this.createAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Students (");

        sb.append(id);
        sb.append(", ").append(fullName);
        sb.append(", ").append(age);
        sb.append(", ").append(gender);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
